### PR TITLE
Upgrade to use the latest googletest (1.11.0)

### PR DESCRIPTION
**Pull request by kostis**
While at it, change the installation instructions and two places in the
code to specify that the unzipped dir should be called `googletest'
instead of having its release version suffix.

### CODE REVIEW

**Comment by kostis** [comment]
I've only tested with `gcc version 8.4.0 (Debian 8.4.0-3)`  (now upgraded to 8.4.0-4) and the build and running `make test` work OK.

Can you try on the newly upgraded machines only or with a newer GCC?

**Comment by davidklaftenegger** [comment]
possibly. The error seems to only occur with ARGO_DEBUG set to ON, so this makes the patch dependent on #41.

**Comment by lundgren87** [comment]
I'm able to reproduce this with `-DARGO_DEBUG=ON` and gcc (Ubuntu 9.3.0-10ubuntu2) 9.3.0 after applying #41 (as it will not build at all without #41 applied). With debug off everything builds as expected.
```
[  2%] Building CXX object src/CMakeFiles/argo.dir/argo.cpp.o
[  5%] Building CXX object src/CMakeFiles/argo.dir/allocators/allocators.cpp.o
[  8%] Building CXX object src/CMakeFiles/argo.dir/env/env.cpp.o
[ 10%] Building CXX object src/CMakeFiles/argo.dir/synchronization/synchronization.cpp.o
[ 13%] Building CXX object src/CMakeFiles/argo.dir/synchronization/cohort_lock.cpp.o
[ 16%] Building CXX object src/CMakeFiles/argo.dir/synchronization/intranode/mcs_lock.cpp.o
[ 18%] Building CXX object src/CMakeFiles/argo.dir/virtual_memory/shm.cpp.o
[ 21%] Linking CXX shared library ../lib/libargo.so
[ 21%] Built target argo
[ 24%] Building CXX object src/backend/mpi/CMakeFiles/argobackend-mpi.dir/mpi.cpp.o
[ 27%] Building CXX object src/backend/mpi/CMakeFiles/argobackend-mpi.dir/swdsm.cpp.o
[ 29%] Linking CXX shared library ../../../lib/libargobackend-mpi.so
[ 29%] Built target argobackend-mpi
[ 32%] Building CXX object tests/googletest/googletest/CMakeFiles/gtest.dir/src/gtest-all.cc.o
[ 35%] Linking CXX static library ../../../lib/libgtest.a
[ 35%] Built target gtest
[ 37%] Building CXX object tests/CMakeFiles/trivialTests-mpi.dir/trivial.cpp.o
[ 40%] Linking CXX executable ../bin/mpi/trivialTests
[ 40%] Built target trivialTests-mpi
[ 43%] Building CXX object tests/CMakeFiles/allocatorsTests-mpi.dir/allocators.cpp.o
[ 45%] Linking CXX executable ../bin/mpi/allocatorsTests
/usr/bin/ld: CMakeFiles/allocatorsTests-mpi.dir/allocators.cpp.o: in function `AllocatorTest_AllocationParametersParsing_Test::TestBody()':
/home/sven/git/argodsm/tests/allocators.cpp:405: undefined reference to `argo::_internal::alloc_params<(argo::allocation)0, (argo::allocation)2, (argo::allocation)4>::initialize'
/usr/bin/ld: /home/sven/git/argodsm/tests/allocators.cpp:406: undefined reference to `argo::_internal::alloc_params<(argo::allocation)0, (argo::allocation)2, (argo::allocation)4>::deinitialize'
/usr/bin/ld: /home/sven/git/argodsm/tests/allocators.cpp:407: undefined reference to `argo::_internal::alloc_params<(argo::allocation)0, (argo::allocation)2, (argo::allocation)4>::synchronize'
/usr/bin/ld: /home/sven/git/argodsm/tests/allocators.cpp:417: undefined reference to `argo::_internal::alloc_params<(argo::allocation)1, (argo::allocation)3, (argo::allocation)5>::no_initialize'
/usr/bin/ld: /home/sven/git/argodsm/tests/allocators.cpp:418: undefined reference to `argo::_internal::alloc_params<(argo::allocation)1, (argo::allocation)3, (argo::allocation)5>::no_deinitialize'
/usr/bin/ld: /home/sven/git/argodsm/tests/allocators.cpp:419: undefined reference to `argo::_internal::alloc_params<(argo::allocation)1, (argo::allocation)3, (argo::allocation)5>::no_synchronize'
/usr/bin/ld: /home/sven/git/argodsm/tests/allocators.cpp:424: undefined reference to `argo::_internal::alloc_params<(argo::allocation)4>::synchronize'
collect2: error: ld returned 1 exit status
make[2]: *** [tests/CMakeFiles/allocatorsTests-mpi.dir/build.make:87: bin/mpi/allocatorsTests] Error 1
make[1]: *** [CMakeFiles/Makefile2:316: tests/CMakeFiles/allocatorsTests-mpi.dir/all] Error 2
make: *** [Makefile:141: all] Error 2

``` 

This error appears to be triggered by using the `-O0` flag for compiling and linking. Any other optimization level appears to optimize this error away (not fix it).

**Comment by davidklaftenegger** [comment]
Thanks @lundgren87

the structs in question are defined in src/allocators/generic_allocator.hpp and `-O0` might disable things that are required even for "correct" (as in standard-conforming) code. So our options here are
a) fix the code such that it works again with -O0
b) use -O1 instead for our debug builds.

**Comment by kostis** [comment]
Issues with `-O0` get fixed if we switch to C++17, which addresses the issue with `static constexpr`s.

**Comment by lundgren87** [comment]
Are we happy to require C++17? I have no objections personally, simply asking for the sake of compatibility with relevant environments.

**Comment by kostis** [comment]
> Are we happy to require C++17? I have no objections personally, simply asking for the sake of compatibility with relevant environments.

What sort of compatibility are you thinking about?  I cannot think of any.

Note that we are only talking about what compiler flags we will pass to GCC when compiling the sources of Argo.

Also since @davidklaftenegger had some concerns about (some of our) machines with old GCC version (e.g. 5.4.0) note that that  [C++17 features are available since GCC 5](https://gcc.gnu.org/projects/cxx-status.html#cxx17) and I've verified that we can use `-std=c++17` even with 5.4.0.

So, let's test and merge this.

**Comment by lundgren87** [comment]
This now works fine on GCC 10.2.
It does **not** appear to work with GCC 5.4.0 on Jason2 or GCC 6.4.0 on David's office PC, building with `ARGO_DEBUG=ON` still produces the same errors when linking the tests.

```
CMakeFiles/allocatorsTests-singlenode.dir/allocators.cpp.o: In function `AllocatorTest_AllocationParametersParsing_Test::TestBody()':
/home/sven/git/argodsm-stage/tests/allocators.cpp:404: undefined reference to `argo::_internal::alloc_params<(argo::allocation)0, (argo::allocation)2, (argo::allocation)4>::initialize'
/home/sven/git/argodsm-stage/tests/allocators.cpp:405: undefined reference to `argo::_internal::alloc_params<(argo::allocation)0, (argo::allocation)2, (argo::allocation)4>::deinitialize'
/home/sven/git/argodsm-stage/tests/allocators.cpp:406: undefined reference to `argo::_internal::alloc_params<(argo::allocation)0, (argo::allocation)2, (argo::allocation)4>::synchronize'
/home/sven/git/argodsm-stage/tests/allocators.cpp:416: undefined reference to `argo::_internal::alloc_params<(argo::allocation)1, (argo::allocation)3, (argo::allocation)5>::no_initialize'
/home/sven/git/argodsm-stage/tests/allocators.cpp:417: undefined reference to `argo::_internal::alloc_params<(argo::allocation)1, (argo::allocation)3, (argo::allocation)5>::no_deinitialize'
/home/sven/git/argodsm-stage/tests/allocators.cpp:418: undefined reference to `argo::_internal::alloc_params<(argo::allocation)1, (argo::allocation)3, (argo::allocation)5>::no_synchronize'
/home/sven/git/argodsm-stage/tests/allocators.cpp:423: undefined reference to `argo::_internal::alloc_params<(argo::allocation)4>::synchronize'
collect2: error: ld returned 1 exit status
```

**Comment by lundgren87** [comment]
It appears as per [this stackoverflow discussion](https://stackoverflow.com/questions/50638053/constexpr-static-data-member-without-initializer/50638400) the solution to require C++17 is correct according to specifications, but GCC fails to correctly/fully implement the C++17 specifications until somewhere around GCC 7 (not sure of the exact version, but I can confirm 5.4-6.4 do not correctly inline static constexpr under `std=c++17`).

**Comment by kostis** [comment]
I think that now is time to merge this.

**Review by davidklaftenegger — APPROVED** [review]

**Review by lundgren87 — APPROVED** [review]
